### ISSUE TITLE
OEL / RHEL RPM GPG Key not imported

### ISSUE THREAD

**Issue by fooshards** [boxcutter/oel#1]
The base box should probably have the following commands issued before exporting the image:

rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY
or
rpm --import /usr/share/rhn/RPM-GPG-KEY 

To allow replications of the native oracle / centos packages to be installed.

**Comment by annawake** [comment]
As far as I understand, use of these repos require an Oracle subscription.  The current OEL boxes force RedHat mode so they don't use any Oracle-specific extensions or the Oracle kernel in the interest of being compatible.  We may add separate "uek" templates that use the default "Oracle" mode, and as far as I understand, only then will this be of benefit (though it also requires a subscription).
